= Design Document of Ifinterp

== TODO
* [x] basic world (just a few rooms with descriptions)
* [x] connections between the rooms
* [x] movement (n, s, e, w)
* [ ] look (around)

* [ ] movement (ne, nw, se, sw)
* [ ] movement (up, dn)
* [ ] movement (enter, leave)

* [ ] examine
* [ ] take, put
* [ ] take from, put into


== Next Time
* Look (around) command.
* TODOs
* Document and comment the source.
* Aliases (e.g. n for go north (or the other way around? Haha.)

== QnA
How will action design allow for conditional overrides?::
E.g. instead of _going_ to a direction, do something instead if the player is
carrying a certain item and, etc.
* A: Idea 1: _World_ and every _thing_ which can be entered (room, region,
  vehicle, etc) has a container of _actions_ (probably a tree or hash-table).
  When action is parsed, check for a matching action starting in the current
  location ascending the hierarchy up to _World_ level, so local overrides would
  be evaluated before regional and global ones.

Should _Room_ obj contain _new*_ (thing, link, etc) methods?::
Or should it be _World_ or perhaps specialised factory altogether?
* A: I'm leaning towards _World_, so you create a new _World_ and through it,
  create the "world" e.g. `world.new_room("Epic Location")`,
  `world.new_link(room_1, room_2)`.

How to handle "can't do"?::
* Should the function responsible print the refusal, or caller?
* Should be easy to customise rejection messages (in general and per-case), how
  to implement it so?

Multiple-inheritance VS composition::
* "Things" will be difficult to represent in a nice class single-inheritance
  tree. E.g. a motorbike is to likely have traits like _self-propelled_,
  _container_, _vehicle_. Should we use multiple-inheritance or composition?

How should doors (locked and otherwise) and hidden exits work?::
* Exit as an object that can be linked to a door?
* Exit can have a "hidden" flag or trait?
* Doors and events could modify the "exits" array to achieve such functionality
  and beyond (maybe unnecessarily complex for common tasks)?

Common traits e.g. `description` as member or inserted into `traits` map?::
* Inserted into map:
** Pros:
*** More "natural" as that's were all traits go.
*** Can be easily overridden in constructor for special cases.
** Notes:
*** (Conjecture -- test) Clarity can be maintained via good coding practices.
** Cons:
*** (Conjecture -- test) Harder to see in object definition.
*** Can be overridden in constructor.

=== Answered
Examine(thing) or thing.examine()?:: A: examine(thing) no need for the class to
always carry and entire function, and if there is need for advanced handling we
can return a callback that would contain the logic.


== Functionality

=== Core

* [ ] Rooms.
* [ ] Connections.
** [ ] Two way.
** [ ] One way (e.g. jump from ledge, supernatural portal).

==== 1
* [ ] Movement (n, s, e, w).
* [ ] Movement (ne, nw, se, sw).
* [ ] Movement (up, dn).
* [ ] Movement (enter, leave).

* [ ] Look (around).
* [ ] Examine.

==== 2
* [ ] Things.

* [ ] Take, put.

==== 3
* [ ] Containers.

* [ ] Take from, put into.

==== 4
* [ ] Light and darkness.


=== Simple Mechanisms
* Doors.
* Locks and keys.


=== Advanced Mechanisms
* Combination locks (e.g. safes, coded locks, code and/or keycard panels).


=== Senses
* [ ] Touch.
* [ ] Hear.
* [ ] Smell.


=== Vehicles
* [ ] Riding (e.g. horse, bicycle, motorbike).
* [ ] Horse-drawn carriage.
* [ ] Elevator (moving room).
* [ ] Train (moving zone).
* [ ] Motor car (drivable room, key, fuel).


=== Passage of time
* Actions (may) take time.
* Waiting, resting, sleeping.


== Tests
* [ ] Duplicate room names should not be allowed.


== Commands
Here commands are described in more detail.

=== Look (Around)
Describe the visible surroundings.

Print the description of the current room, any area visible things (e.g. zone
and global backdrops), and things visible in the room.

==== Common Aliases
Look around.


=== Examine
Give more details about an object, i.e. print description, contents (if
container that is open or transparent), state (if device), etc.
